// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEeOPqJbd9L6sG09KHooy5reM51Gwt2HE',
    appId: '1:912859054164:web:3ed422dfd87a6da50f6dc1',
    messagingSenderId: '912859054164',
    projectId: 'labassignment-f14d2',
    authDomain: 'labassignment-f14d2.firebaseapp.com',
    storageBucket: 'labassignment-f14d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmJpvZ7wRZ_7mFs34TS8Z862sji9xGmKo',
    appId: '1:912859054164:android:2769a8149c495dce0f6dc1',
    messagingSenderId: '912859054164',
    projectId: 'labassignment-f14d2',
    storageBucket: 'labassignment-f14d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWFXxMrr4BaOIZ-BHE18UIWOnT_lHuvjk',
    appId: '1:912859054164:ios:4bf8885bbde7bc940f6dc1',
    messagingSenderId: '912859054164',
    projectId: 'labassignment-f14d2',
    storageBucket: 'labassignment-f14d2.appspot.com',
    iosClientId: '912859054164-ju1qo7dqcb02vfmd3es18nmegvmks2br.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWFXxMrr4BaOIZ-BHE18UIWOnT_lHuvjk',
    appId: '1:912859054164:ios:4bf8885bbde7bc940f6dc1',
    messagingSenderId: '912859054164',
    projectId: 'labassignment-f14d2',
    storageBucket: 'labassignment-f14d2.appspot.com',
    iosClientId: '912859054164-ju1qo7dqcb02vfmd3es18nmegvmks2br.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLabAssignment',
  );
}
